### ISSUE TITLE
No update of config inside pianolux.local

### ISSUE THREAD

**Issue by caribouman** [serifpersia/pianolux-esp32#5]
Hi, the change made on web interface is not transmitted to esp32, no apply button,

**Comment by serifpersia** [comment]
> Hi, the change made on web interface is not transmitted to esp32, no apply button,

Please elaborate more what are you trying to do, I have 0 clue about what issue are you trying to present.
Share details of things you are trying to do, the desired outcome you want from the feature of pianolux esp32 and the issue you are having with that feature.
