### ISSUE TITLE
Controls issue through web application

### ISSUE THREAD

**Issue by caribouman** [serifpersia/pianolux-esp32#6]
Board type:

ESP32 S3

Install method:

    - Auto install

Hi , the install is ok , after the led display the ip ... it s possible to go to pianolux.local

but on this web display all controls are not working, you can change  animation or light color... you can change anything on the page, nothing happens on the led. it s like the controls are not saved or applied

i can send midi via rtp midi on the ip of the pianolux and at one moment "the ip led display disappear" and it start to work and lighting the led in front of my key i press, but i don t have any control on colors or display time through the web application.

and another issue just to mention :when i try to use synthesia to midi out via rtp midi, the light reacts to noteOn, but lot of time noteOff doesn t stop the led(perhaps latency).

**Comment by serifpersia** [comment]
> Board type:
> 
> ESP32 S3
> 
> Install method:
> 
> ```
> - Auto install
> ```
> 
> Hi , the install is ok , after the led display the ip ... it s possible to go to pianolux.local
> 
> but on this web display all controls are not working, you can change animation or light color... you can change anything on the page, nothing happens on the led. it s like the controls are not saved or applied
> 
> i can send midi via rtp midi on the ip of the pianolux and at one moment "the ip led display disappear" and it start to work and lighting the led in front of my key i press, but i don t have any control on colors or display time through the web application.
> 
> and another issue just to mention :when i try to use synthesia to midi out via rtp midi, the light reacts to noteOn, but lot of time noteOff doesn t stop the led(perhaps latency).

I think the bluetooth feature I added is causing the board to not work properly. I removed bluetooth from esp32 I will remove it for s3 as well and update the auto install firmware. When you see this reply it should be updated. Do auto install again and report if you still have unresponsive interface. To verify that you are using latest auto install website check last modified label if you see the date matching todays date its latest version of the website with updated firmware in which I removed ble for now. 
Please report after you install new firmware if it has any issues like before.
Thanks

Edit: I updated the auto install and release files, ble is added back but you turn it on with buttons so it should resolve your issue.

![image](https://github.com/serifpersia/pianolux-esp32/assets/62844718/02b7e2ce-44f5-4247-8bab-6ed49d70fa96)

![image](https://github.com/serifpersia/pianolux-esp32/assets/62844718/3f0cb7a9-7d52-4895-beb2-64e40e4288c3)

**Comment by caribouman** [comment]
Hi , yes thank you , it s working now, controls are working  on the page , and fx led works also to move the led after a3 and the one after and latency seems also a bit less (i have to test a bit more),  perfect. i will try to buy a power for leds because i think sometimes the esp is rebooting time to time but it works
great job

**Comment by serifpersia** [comment]
> Hi , yes thank you , it s working now, controls are working on the page , and fx led works also to move the led after a3 and the one after and latency seems also a bit less (i have to test a bit more), perfect. i will try to buy a power for leds because i think sometimes the esp is rebooting time to time but it works great job

If you have usb midi device you can connect it directly to s3 usb otg port(dual port board) if you have single usb port try diy usb otg to jumper pins adapter and use 19 20 5v and gnd pins to create usb connection, if you use wifi midi router network mostly likely is causing delays, I recommend you to try AP mode(short pin 16 to gnd and reset the board) for skipping router and use esp32 network instead which should help you with latency. But since you have s3 I recommend usb connection bc s3 supports it,
